
package:
    name: openbabel
    version: 2.4.99

source:
    fn: openbabel-fix-msvc.zip
    url: https://github.com/mwojcikowski/openbabel/archive/fix-msvc.zip
    # git_url: https://github.com/openbabel/openbabel.git
    # git_rev: master
    patches:
        # - fix_library_path_search.diff
        # - fix_data_path.diff
        # - fix_babel_test_paths.diff
        # - fix_python_3.6.diff  # [py3k]

build:
    number: 3
    detect_binary_files_with_prefix: true

requirements:
    build:
        - gcc     # [linux]
        - llvm    # [osx]
        - cmake
        - zlib
        - swig
        - eigen
        - bzip2
        - python
        - libxml2
        - cairo
    run:
        - python
        - libgcc  # [linux]
        - zlib
        - libxml2
        - cairo
test:
  imports:
    - openbabel
    - pybel
  commands:
    - obabel --help
    - obabel -:c1ccccc1 --gen3d -omol2
    - obabel -:c1ccccc1 --gen3d -oinchi
    - obabel -:c1ccccc1 -opng -O img.png

about:
    home: http://www.openbabel.org/
    license: GPLv2
    summary: "A chemical toolbox designed to speak the many languages of chemical data"
