sudo: required
services:
  - docker
os:
- osx
- linux
language: c
env:
  matrix:
  - CONDA_PY=27
  - CONDA_PY=35
  - CONDA_PY=36
  - CONDA_PY=37
  global:
  - secure: "aZ6BpJ7eJ3OxzlCQxVngJWP6aWL0nr0yEAywEqvvkVGDq3QVVmcu18VqgmiPtuLn2+FWY4zK8WoiRE2nXFtoqKcGxlMTnNKfLCC6+jpWCpwSx1Tkx0mLGFaZGTsf0wlgUnYiVkVWzEzgxhXR27qiiUYpPcbqBEwdFkq6QVNapRc1yGahHu1h4XdamN46sH/ZEX3zpkUsm5zZRPbd4rQXMNNWlEAKz6ZEx00q9x+Rpx9nlfERQ3AIZ/bJAmMr7XmaLIxlB0XvEOs3Z4avUY8thmjek6CK9JAxyRt85GWviDuqX87YoCl87bDzg5mOIRM/gpnEvvDDxeVq44Ld06vQd45whxYHL2PaEFSGtuSBCegP7YLCMzGHjRyPV1obvNNwL2XkEY3Ell17HD0NNqmP4ux9pI1W0cYB1g+2YpnP9uWgQ6lZ1y50rBizNu4wdKSyXzEGCUgiRxOgaGAW8pQSKF0ZbC/RxUB4Z+78Z50u1PZzYMUr4f9jiAeqTr7Rla5Erd2J5MSVeozbIvVCFUphrI/lA7yCy50Qbv0Yv8bJVd+ZxJZA6rWUrmZ/457ya+ZOqG58MIc/ZYaQggZoyOcunwAjAefkNA6OBOazHiVcSF0bJWi+vJpDp65f64tbtDzcOK9S4DITYm+t1LkNfi7+JvPbodBrqZcVlXjHXaMPacY="
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then scripts/travis/run-linux.sh; else scripts/travis/run-osx.sh; fi;
