sudo: required
services:
  - docker
os:
- osx
- linux
language: c
env:
  matrix:
  - CONDA_PY=27
  - CONDA_PY=34
  - CONDA_PY=35
  - CONDA_PY=36
  - CONDA_PY=37
  global:
  - secure: "iDjaNGwcnk2mXt/TxZrwrD1pB2ulgQL4FRNsApqkf4qmJ8djmMP1V7dM9bzKL0nU1IZsRbIDSAw+bZYKX2KSg4ZWTnZP3mcwBm2a2+VXm1+8O2I86+3VqP5y8vZorAeh3/Kj5wGpUN25dqtytwxmtNFdyly8i3vi4Gj6EHiASEGthvAHjq5s5hWLZILHtJkCHnjpyrsqUhPAlHE06DMhGQBuvqR059zu5ozW506pj80AFStntjVJY3rPBXZ38i4sbDxxxlL3kKhK1Up0mLuI0N90omcEQVyJFsjkISCMptJl4SXLbDvtIVVvMqSnpMt5/d2WUXO23tVfgBevlDAEeskMdO3tt41DQ5f2oUjhSFBlKCMwIt6wuj344QsHaEsd8+d8R2jYxyxh1b42YgmYuWgveTwTImmou0Pegr1pCh/nygTbxnrm+PSb2RWdZ8q5xnIXs1F7Ih8M0WoG5+v5Fef07ZcTSSnKLukL+JkM54W8uXePEd9wlDCxHZKVJcESwEbu1ifft1ZfeEZjf9atSv3KdIXL+V/p4rsH2y3sI2oFp7uw5MT7WLibrOpqcHdbffeC2dgVabzD93x0p09VWECf0MyaIHsBonXwpTt1THoSppi5pCK+g3IGxj7YO2ub1VmfAc+tAoxUxedFADlJlNltndZ03EgQTAxNw32oqRs="
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then scripts/travis/run-linux.sh; else scripts/travis/run-osx.sh; fi;
