sudo: required
os:
- osx
- linux
language: c
env:
  matrix:
  - CONDA_PY=27
  - CONDA_PY=34
  - CONDA_PY=35
  global:
  # secure ANACONDA_TOKEN goes here
  - secure:
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then scripts/travis/run-linux.sh; else scripts/travis/run-osx.sh;; fi;
